### ISSUE TITLE
Light Overlay not updating when using immersive portals

### ISSUE THREAD

**Issue by NovaXe** [SchmarrnDevs/Lighty#39] opened 2023-08-11 20:21 UTC
The overlay doesn't update to newly placed light sources until another block is placed.
Instance description:
Quilt w/ quilted fabric api
immersive portals
sodium
lighty

**Comment by andi-makes** [comment] 2023-08-12 05:42
Thank you for reporting the issue! The incompat with immersive portals is already known and tracked in Issue #29.

Is sodium required for the issue to reproduce? Last time I tried to reproduce it I didn't need sodium installed.

The problem: Immersive Portals changes some Minecraft internals Lighty relies on for detecting light updates. I know what internal stuff it breaks, but not how and what an alternative solution would be.

For now, either remove immersive portals or Lighty from your instance. Because immersive portals breaks a lot of other mods as well, this issue is currently of low priority. I'll create an issue over at their repo when I've looked at the issue more deeply, maybe there is something that immersive portals can do to fix it.

I am closing this Issue in favor of tracking everything in Issue #29.

**Closed as completed by andi-makes** 2023-08-12 05:42 UTC
Labels: bug, duplicate, reproduced
