### ISSUE TITLE
The overlay appears/disappears whenever "E" or "escape" is pressed.

### ISSUE THREAD

**Issue by BOROWA1709** [SchmarrnDevs/Lighty#72] opened 2024-07-20 12:55 UTC
The overlay appears/disappears whenever "E" or "escape" is pressed. My keybinds for the mod are not "E" nor "escape" and it only started happening recently.

**Comment by andi-makes** [comment] 2024-07-21 07:00
Thank you for opening this issue!

I need some further information about this bug:

- What version of Lighty are you using?
- What Modloader? (NeoForge, Fabric)
- What Minecraft version?
- Are you using any other mods as well?
  - If so, does the bug occur with just Lighty installed? If not, please try to figure out which other mod is causing the issue. Alternatively, a list of all used mods might also already help, but resolving this will take longer if I have to find the causing mod-combo myself.

You've said that this only started happening recently. Is there anything you did, like updating Lighty or another mod, that could have caused this?

Thanks again for reporting this issue, and hopefully we will find a solution for it soon!

**Comment by andi-makes** [comment] 2024-08-12 09:03
Because I cannot reproduce this issue with just Lighty, and there was no further information provided, I am closing this issue.

Feel free to reopen this issue if you want to provide further information, we can look at solving this then.

**Closed as completed by andi-makes** 2024-08-12 09:03 UTC
Labels: bug, question
